// <auto-generated />
using Ktrgk2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ktrgk2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250307071602_UpdateHangHoa")]
    partial class UpdateHangHoa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ktrgk2.Models.HangHoa", b =>
                {
                    b.Property<string>("MaHangHoa")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHoa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaHangHoa");

                    b.ToTable("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
